### PR TITLE
Update to Laravel 5.5

### PR DESCRIPTION
**Pull request by cfreak**
Change of composer.json to fit Laravel 5.5

### CODE REVIEW

**Comment by jkniest** [comment]
I would also add package auto discovery. See https://laravel.com/docs/5.5/packages#package-discovery

**Comment by cfreak** [comment]
Okay is added. Please accept PR.

**Comment by jkniest** [comment]
@cfreak, sorry I can't merge this PR. But I would also really appreciate it :)

**Comment by akaamitgupta** [comment]
@cfreak Thanks for the PR and sorry for the late reply. Was on vacation for few days.

I have merged it and will release a new version soon after doing some testing and updating the readme file.

In this new version, we will add the slack notifications also. Hope you guys like it.

**Comment by jkniest** [comment]
Nice!

**Pull request merged**
